"""Add password field to User

Revision ID: 59535b117b98
Revises: a69fd67d1959
Create Date: 2025-10-04 11:33:04.148012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59535b117b98'
down_revision = 'a69fd67d1959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###
